### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by Dazmed707** [oscar0812/java-apk-obfuscator#1]
Video tutorial for ofuscate apk ?
GUI software for using tool?

**Comment by oscar0812** [comment]
@Dazmed707 thank you for your patience. I can work on a GUI for this obfuscator if enough people want it. For now, you can download a free java IDE (such as intellij) and import the project, or you can use it as a jar artifact.

**Comment by sneddy781** [comment]
hi, im new on java, im a developper on unity c# , i imported the whole project, added java path as intellij asked to me, i added my decompiled apk folder to src, but the run button is still gray, can you help me please ?

**Comment by sneddy781** [comment]
i managed to make it work but i get this error message (: ...\src\com\oscar0812\obfuscation\MainClass.java:42:18
java: exception java.io.IOException is never thrown in body of corresponding try statement) of apk tool only when i import newer version of apktool, otherwise i get this error : brut.androlib.AndrolibException: brut.directory.DirectoryException: java.util.zip.ZipException: Invalid CEN header (invalid zip64 extra data field size)


anyway to fix this ?

**Comment by sneddy781** [comment]
normal apktool works perfectly, is there a way to obfuscate only smali, i can recompile via apktool later
